#!/bin/bash

set -e

# Check to see if there is a node_modules folder
if [ "$(ls -A /tmp/src/node_modules)" ]; then
	echo "---> Removing the node_modules folder"
	rm -rf /tmp/src/node_modules
fi

chmod 775 -R /tmp/src/.

echo "---> Installing application source"
cp -Rfp /tmp/src/. ./

if [ ! -z $HTTP_PROXY ]; then
	echo "---> Setting npm http proxy to $HTTP_PROXY"
	npm config set proxy $HTTP_PROXY
fi

if [ ! -z $http_proxy ]; then
	echo "---> Setting npm http proxy to $http_proxy"
	npm config set proxy $http_proxy
fi

if [ ! -z $HTTPS_PROXY ]; then
	echo "---> Setting npm https proxy to $HTTPS_PROXY"
	npm config set https-proxy $HTTPS_PROXY
fi

if [ ! -z $https_proxy ]; then
	echo "---> Setting npm https proxy to $https_proxy"
	npm config set https-proxy $https_proxy
fi

# Change the npm registry mirror if provided
if [ ! -z "$NPM_MIRROR" ]; then
	echo "---> Setting the npm package mirror to $NPM_MIRROR"
	npm config set registry $NPM_MIRROR
fi

if [ "$(ls /tmp/artifacts/ 2>/dev/null)" ]; then
  echo "---> Restoring build artifacts..."
  mv /tmp/artifacts/node_modules ./
fi

echo "---> Building your Node application from source"
echo -e "Current git config"
git config --list
if [ ! -z "$YARN_ENABLED" ]; then
	echo "---> Using 'yarn install' with YARN_ARGS"
	yarn install $YARN_ARGS
	yarn build
else
	echo "---> Installing dependencies"
	echo "---> Using 'npm install'"
	npm install -d
	npm run build
	echo "---> Cleaning up npm cache"
	rm -rf .npm
	# echo "---> Setting directory write permissions"
	# exec chmod -R g+rw .
fi

echo "---> Building and Installing Web Application from source..."
if [ -f /tmp/src/nginx.conf ]; then
  mv /tmp/src/nginx.conf /etc/nginx/nginx.conf
fi

if [ "$(ls -A /tmp/src)" ]; then
  mv ./$OUTPUT_DIR/* /usr/share/nginx/html/
fi
