#!/bin/bash

set -e

echo -e "Running as user $(id)"

echo "Running this container is only recommended when running in test or development."
echo "It is recommended to use this s2i image as a pure builder image and use it with an openshift chain buildhttps://docs.okd.io/latest/dev_guide/builds/advanced_build_operations.html#dev-guide-chaining-builds"

npx serve -s $DEPLOY_DIR -l 8080

# # Allow debugging the builder image itself, by using:
# # $ docker run -it bucharestgold/centos-s2i-nodejs --debug
[ "$1" == "--debug" ] && exec /bin/bash
