#!/bin/bash

set -e

# We will turn off daemonizing for the nginx process so that the container
# doesn't exit after the process runs.
echo -e "Running as user $(id)"
echo "starting nginx server with daemon off"
exec /usr/sbin/nginx -g "daemon off;"

# # Allow debugging the builder image itself, by using:
# # $ docker run -it bucharestgold/centos-s2i-nodejs --debug
[ "$1" == "--debug" ] && exec /bin/bash
