#!/bin/bash

set -e

echo -e "Running as user $(id)"

echo "Maybe you don't really want to do this and use a chained build instead?"

npx serve -s $DEPLOY_DIR -l 8080

# # Allow debugging the builder image itself, by using:
# # $ docker run -it bucharestgold/centos-s2i-nodejs --debug
[ "$1" == "--debug" ] && exec /bin/bash
