#!/bin/sh

cat <<EOF
This is a S2I base image for Web Applications:
To use it, install S2I: https://github.com/openshift/source-to-image

Sample invocation:
s2i build https://github.com/bucharest-gold/centos7-s2i-web-app --context-dir=test/test-react-app/ bucharestgold/centos7-s2i-web-app:latest sample-app

You can then run the resulting image via:
docker run -p 8080:8080 sample-app
EOF
